name: Make Data

on:
  push:

jobs:
  make-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - run: npm install

      - run: node script/words.mjs

      - run: node script/phrases.mjs

      - id: diff
        run: git diff-index --quiet HEAD -- || echo "::set-output name=has_changes::true"

      - if: ${{ steps.diff.outputs.has_changes }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -am "build: make data at `date`"
          git push origin master
